services:
  mariadb:
    build: ./requirements/mariadb
    container_name: mariadb
    restart: always
    env_file:
      - .env
    secrets:
      - sql_password
    volumes:
      - mariadb:/var/lib/mysql
    networks:
      - inception

  wordpress:
    build: ./requirements/wordpress
    container_name: wordpress
    restart: always
    depends_on:
      - mariadb
    env_file:
      - .env
    secrets:
      - wp_admin_password
      - wp_user_password
      - sql_password
    volumes:
      - wordpress:/var/www/html
    networks:
      - inception

  nginx:
    build: ./requirements/nginx
    container_name: nginx
    restart: always
    depends_on:
      - wordpress
    ports:
      - "443:443"
    volumes:
      - wordpress:/var/www/html
    networks:
      - inception

networks:
  inception:
    driver: bridge

secrets:
  sql_password:
    file: ../secrets/sql_password.txt
  wp_admin_password:
    file: ../secrets/wp_admin_password.txt
  wp_user_password:
    file: ../secrets/wp_user_password.txt

volumes:
  mariadb:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/mschyns/data/mariadb

  wordpress:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/mschyns/data/wordpress
